{% set version = '1.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nglviewer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/NGLVieweR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/NGLVieweR/NGLVieweR_{{ version }}.tar.gz
  sha256: c0994a546a1d56acd6bb3ff0615d8b839d5e790e265ec92453ea1935326d5f95

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmlwidgets
    - r-magrittr
    - r-shiny
  run:
    - r-base
    - r-htmlwidgets
    - r-magrittr
    - r-shiny

test:
  commands:
    - $R -e "library('NGLVieweR')"           # [not win]
    - "\"%R%\" -e \"library('NGLVieweR')\""  # [win]

about:
  home: https://github.com/nvelden/NGLVieweR
  license: MIT
  summary: Provides an 'htmlwidgets' <https://www.htmlwidgets.org/> interface to 'NGL.js' <http://nglviewer.org/ngl/api/>.
    'NGLvieweR' can be used to visualize and interact with protein databank ('PDB')
    and structural files in R and Shiny applications. It includes a set of API functions
    to manipulate the viewer after creation in Shiny.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: NGLVieweR
# Title: Interactive 3D Visualization of Molecular Structures
# Version: 1.3.1
# Authors@R: c( person("Niels", "van der Velden", role = c("aut", "cre"), email = "n.s.j.vandervelden@gmail.com"), person("Alexander", "Rose", role = "cph", comment = 'NGL.js library'))
# Maintainer: Niels van der Velden <n.s.j.vandervelden@gmail.com>
# Description: Provides an 'htmlwidgets' <https://www.htmlwidgets.org/> interface to 'NGL.js' <http://nglviewer.org/ngl/api/>. 'NGLvieweR' can be used to visualize and interact with protein databank ('PDB') and structural files in R and Shiny applications. It includes a set of API functions to manipulate the viewer after creation in Shiny.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# Imports: htmlwidgets, magrittr, tools, shiny
# Suggests: knitr, webshot, markdown, rmarkdown
# VignetteBuilder: knitr
# URL: https://github.com/nvelden/NGLVieweR
# BugReports: https://github.com/nvelden/NGLVieweR/issues
# NeedsCompilation: no
# Packaged: 2021-05-31 10:37:06 UTC; nvandervelden
# Author: Niels van der Velden [aut, cre], Alexander Rose [cph] (NGL.js library)
# Repository: CRAN
# Date/Publication: 2021-06-01 07:00:01 UTC
